const SUPABASE_URL='https://ukmjptafczxhdcqcpxrv.supabase.co';
const SUPABASE_KEY='sb_publishable_j6Zj02g3nNxzeqXt5vvnmw_LuHlR2tJ';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=id=>document.getElementById(id);let current=null;
async function init(){const {data:{session}}=await sb.auth.getSession();if(session)showDash();else $('loginBox').classList.remove('hidden')}
$('login').onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)$('loginMsg').textContent=error.message;else showDash()};
$('logout').onclick=async()=>{await sb.auth.signOut();location.reload()};
async function showDash(){$('loginBox').classList.add('hidden');$('dashboard').classList.remove('hidden');$('logout').classList.remove('hidden');await loadSettings();await loadProducts()}
async function loadSettings(){const {data,error}=await sb.from('site_settings').select('*').limit(1).maybeSingle();if(error)return;if(data){$('storeName').value=data.store_name||'';$('whatsapp').value=data.whatsapp||'';$('tiktok').value=data.tiktok||'';$('primaryColor').value=data.primary_color||'#e9a7bd';$('secondaryColor').value=data.secondary_color||'#c8b8e8';$('paymentAr').value=data.payment_info_ar||'';$('paymentEn').value=data.payment_info_en||'';$('deliveryAr').value=data.delivery_info_ar||'';$('deliveryEn').value=data.delivery_info_en||''}}
$('saveSettings').onclick=async()=>{const {data:first}=await sb.from('site_settings').select('id').limit(1).maybeSingle();const obj={store_name:$('storeName').value,whatsapp:$('whatsapp').value.replace(/\D/g,''),tiktok:$('tiktok').value,primary_color:$('primaryColor').value,secondary_color:$('secondaryColor').value,payment_info_ar:$('paymentAr').value,payment_info_en:$('paymentEn').value,delivery_info_ar:$('deliveryAr').value,delivery_info_en:$('deliveryEn').value,updated_at:new Date().toISOString()};const q=first?sb.from('site_settings').update(obj).eq('id',first.id):sb.from('site_settings').insert(obj);const {error}=await q;$('settingsMsg').textContent=error?error.message:'تم حفظ الإعدادات ✅'};
async function loadProducts(){const {data,error}=await sb.from('products').select('*').order('created_at',{ascending:false});$('adminProducts').innerHTML=error?'<p>تعذر تحميل المنتجات.</p>':(data||[]).map(p=>`<div class="admin-item"><img src="${p.image_url||'assets/lola-logo.jpg'}"><div><b>${esc(p.name_ar)}</b><div>${Number(p.price_egp).toFixed(2)} جنيه · ${p.active?'ظاهر':'مخفي'}</div></div><div class="admin-actions"><button onclick="editProduct('${p.id}')">تعديل</button><button onclick="toggleProduct('${p.id}',${!p.active})">${p.active?'إخفاء':'إظهار'}</button><button onclick="deleteProduct('${p.id}')">حذف</button></div></div>`).join('')||'<p>لم تتم إضافة منتجات بعد.</p>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
$('saveProduct').onclick=async()=>{const id=$('productId').value;let image_url=current?.image_url||null;const file=$('image').files[0];if(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${crypto.randomUUID()}.${ext}`;const up=await sb.storage.from('product-images').upload(path,file,{upsert:false,contentType:file.type});if(up.error){$('productMsg').textContent=up.error.message;return}image_url=sb.storage.from('product-images').getPublicUrl(path).data.publicUrl}
const obj={name_ar:$('nameAr').value,name_en:$('nameEn').value,description_ar:$('descAr').value,description_en:$('descEn').value,price_egp:Number($('price').value||0),category:$('category').value,image_url,active:$('active').checked,updated_at:new Date().toISOString()};let q=id?sb.from('products').update(obj).eq('id',id):sb.from('products').insert(obj);const {error}=await q;if(error)$('productMsg').textContent=error.message;else{$('productMsg').textContent='تم حفظ المنتج ✅';resetForm();loadProducts()}};
window.editProduct=async id=>{const {data}=await sb.from('products').select('*').eq('id',id).single();current=data;$('productId').value=data.id;$('nameAr').value=data.name_ar||'';$('nameEn').value=data.name_en||'';$('descAr').value=data.description_ar||'';$('descEn').value=data.description_en||'';$('price').value=data.price_egp||0;$('category').value=data.category||'skin';$('active').checked=data.active;$('cancelEdit').classList.remove('hidden');window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})};
window.toggleProduct=async(id,val)=>{await sb.from('products').update({active:val,updated_at:new Date().toISOString()}).eq('id',id);loadProducts()};
window.deleteProduct=async id=>{if(!confirm('حذف المنتج؟'))return;await sb.from('products').delete().eq('id',id);loadProducts()};
function resetForm(){current=null;$('productId').value='';['nameAr','nameEn','descAr','descEn','price'].forEach(id=>$(id).value='');$('active').checked=true;$('image').value='';$('cancelEdit').classList.add('hidden')}$('cancelEdit').onclick=resetForm;$('refresh').onclick=loadProducts;init();
